cluster_permissions:
  - cluster_composite_ops_ro

index_permissions:
  - index_patterns:
      - "cust-a-*"
    allowed_actions:
      - read

tenant_permissions:
  - tenant_patterns:
      - "customer-a"
    allowed_actions:
      - kibana_all_read
